/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;

import com.tcs.tallerListas.beans.Estudiante;
import jdk.nashorn.internal.objects.NativeError;
import org.checkerframework.checker.units.qual.A;

import java.io.File;
import java.io.FileNotFoundException;
import java.security.PublicKey;
import java.util.ArrayList;
import java.util.Scanner;


public class IngresoEstudiantes {

	public static void main(String[] args) {

		System.out.println("################ Ingreso de estudiantes ################");

		ArrayList<Estudiante> arrayEstudiantes= new ArrayList<Estudiante>();
		ArrayList<Estudiante> arrayJardin =new ArrayList<>();
		ArrayList<Estudiante> arrayPrimero =new ArrayList<>();
		ArrayList<Estudiante> arraySegundo = new ArrayList<>();
		ArrayList<Estudiante> arrayTercero = new ArrayList<>();
		ArrayList <Estudiante> arrayCuarto = new ArrayList<>();
		ArrayList<Estudiante> arrayQuinto = new ArrayList<>();

		try {
			File file = new File("src/main/resources/data.txt");
			Scanner data = new Scanner(file);
			//Scanner data = new Scanner(new File("src/main/resources/data.txt"));
			while (data.hasNextLine()) {
				String[] estData = data.nextLine().split(",");

					Estudiante estudiante =new Estudiante();
					estudiante.setTipoDocumento(estData[0]);
					estudiante.setNumeroDocumento(estData[1]);
					estudiante.setNombre(estData[2]);
					estudiante.setEdad(Integer.parseInt(estData[3]));
					estudiante.setGrado(estData[4]);
					estudiante.setRepetira_anio(estData[5]);

					arrayEstudiantes.add(estudiante);

			}
				data.close();

		} catch (FileNotFoundException e) {

			System.out.println("El archivo no fue encontrado: "+ e.getMessage());
		}

		catch (NumberFormatException e) {

			System.out.println("Error de conversion de datos: "+ e);
		}
		int tamano=arrayEstudiantes.size();

		for (int i=0; i< arrayEstudiantes.size();i++){
			Estudiante auxestudiante = arrayEstudiantes.get(i);

			System.out.println("TipoDocumento: "+auxestudiante.getTipoDocumento() +
					           " NumeroDocumento: "+auxestudiante.getNumeroDocumento()+
								" Nombre: "+auxestudiante.getNombre()+
								" Edad: "+auxestudiante.getEdad()+
								" Grado: "+auxestudiante.getGrado()+
								"Repertira anio: "+auxestudiante.getRepetira_anio()
						);



		}
		System.out.println("El numero de estudiantes del archivo es: "+tamano);



		int cont=0;
		for(int i=0;i<arrayEstudiantes.size();i++){
			if (arrayEstudiantes.get(i).getEdad()>=6 && arrayEstudiantes.get(i).getEdad()<=10){
			cont++;}
		}
		System.out.println(" la Cantidad de estudiantes entre 6 y 10 años es: "+ cont);

		for (int i=0; i<arrayEstudiantes.size();i ++){
			Estudiante estudianteJardin =new Estudiante();
			Estudiante estudiantePrimero = new Estudiante();
			Estudiante estudianteSegundo = new Estudiante();
			Estudiante estudianteTercero = new Estudiante();
			Estudiante estudianteCuarto = new Estudiante();
			Estudiante estudianteQuinto = new Estudiante();
			if (arrayEstudiantes.get(i).getGrado().equals("Jardin")){
				estudianteJardin.setNombre(arrayEstudiantes.get(i).getNombre());
				estudianteJardin.setGrado(arrayEstudiantes.get(i).getGrado());
				estudianteJardin.setTipoDocumento(arrayEstudiantes.get(i).getTipoDocumento());
				estudianteJardin.setEdad(arrayEstudiantes.get(i).getEdad());

				arrayJardin.add(estudianteJardin);

				//System.out.println(arrayJardin.get(i).getNombre()+arrayJardin.get(i).getGrado());

			}

			else if(arrayEstudiantes.get(i).getGrado().equals("Primero")){
				estudiantePrimero.setNombre(arrayEstudiantes.get(i).getNombre());
				estudiantePrimero.setGrado(arrayEstudiantes.get(i).getGrado());
				estudiantePrimero.setTipoDocumento(arrayEstudiantes.get(i).getTipoDocumento());
				estudiantePrimero.setEdad(arrayEstudiantes.get(i).getEdad());
				arrayPrimero.add(estudiantePrimero);



			} else  if(arrayEstudiantes.get(i).getGrado().equals("Segundo")){

				estudianteSegundo.setNombre(arrayEstudiantes.get(i).getNombre());
				estudianteSegundo.setGrado(arrayEstudiantes.get(i).getGrado());
				estudianteSegundo.setTipoDocumento(arrayEstudiantes.get(i).getTipoDocumento());
				estudianteSegundo.setEdad(arrayEstudiantes.get(i).getEdad());
				arraySegundo.add(estudianteSegundo);


			} else  if(arrayEstudiantes.get(i).getGrado().equals("Tercero")){

				estudianteTercero.setNombre(arrayEstudiantes.get(i).getNombre());
				estudianteTercero.setGrado(arrayEstudiantes.get(i).getGrado());
				estudianteTercero.setTipoDocumento(arrayEstudiantes.get(i).getTipoDocumento());
				estudianteTercero.setEdad(arrayEstudiantes.get(i).getEdad());
				arrayTercero.add(estudianteTercero);


			}
			else  if(arrayEstudiantes.get(i).getGrado().equals("Cuarto")){

				estudianteCuarto.setNombre(arrayEstudiantes.get(i).getNombre());
				estudianteCuarto.setGrado(arrayEstudiantes.get(i).getGrado());
				estudianteCuarto.setTipoDocumento(arrayEstudiantes.get(i).getTipoDocumento());
				estudianteCuarto.setEdad(arrayEstudiantes.get(i).getEdad());
				arrayCuarto.add(estudianteCuarto);


			}
			else  if(arrayEstudiantes.get(i).getGrado().equals("Quinto")){

				estudianteQuinto.setNombre(arrayEstudiantes.get(i).getNombre());
				estudianteQuinto.setGrado(arrayEstudiantes.get(i).getGrado());
				estudianteQuinto.setTipoDocumento(arrayEstudiantes.get(i).getTipoDocumento());
				estudianteQuinto.setEdad(arrayEstudiantes.get(i).getEdad());
				arrayQuinto.add(estudianteQuinto);


			}

		}

		for (int i=0;i<arrayJardin.size();i++){


			System.out.println("Los estudiantes del Grado Jardin son: "+arrayJardin.get(i).getNombre()+arrayJardin.get(i).getGrado());

		}

		for( int i=0;i<arrayPrimero.size();i++){
			System.out.println(arrayPrimero.get(i).getNombre()+arrayPrimero.get(i).getGrado());

		}

		for( int i=0;i<arraySegundo.size();i++){
			System.out.println(arraySegundo.get(i).getNombre()+arraySegundo.get(i).getGrado());

		}

		for( int i=0;i<arrayTercero.size();i++){
			System.out.println(arrayTercero.get(i).getNombre()+arrayTercero.get(i).getGrado());

		}

		for( int i=0;i<arrayCuarto.size();i++){
			System.out.println(arrayCuarto.get(i).getNombre()+arrayCuarto.get(i).getGrado());

		}

		for( int i=0;i<arrayQuinto.size();i++){
			System.out.println(arrayQuinto.get(i).getNombre()+arrayQuinto.get(i).getGrado());

		}

		for(int i=0;i<arrayEstudiantes.size();i++){
			if(arrayEstudiantes.get(i).getTipoDocumento().equals("TI")){

				System.out.println("edad del estudiante es: "+arrayEstudiantes.get(i).getEdad()+ " "+
						"grado del estudiante es: "+arrayEstudiantes.get(i).getGrado());


			}



		}
		for(int i=0; i<arrayEstudiantes.size();i++){
			if(arrayEstudiantes.get(i).getRepetira_anio().equals("SI")){
				System.out.println("Los ninos que repetiran el anio son: "+
						arrayEstudiantes.get(i).getNombre()+
						arrayEstudiantes.get(i).getRepetira_anio()
				);

			}



		}

	}


}
